name: EasyScan
description: A Crossplatform document scanning app that can convert images to
  pdf in a simple tap.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.13.2
  pdf: ^1.10.0
  open_file: null
  google_fonts: ^1.1.0
  image_cropper: ^1.3.0
  image_picker: ^0.6.7+4
  native_pdf_renderer: ^2.3.2
  permission_handler: ^5.0.1+1
  flutter_image_editor: ^1.2.0


dev_dependencies:
  lint: ^1.2.0
flutter:
  uses-material-design: true
